# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
from django.db import models
from django.db.models import deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
